### ISSUE TITLE
Add collaborators

### ISSUE THREAD

**Issue by kaiiam** [jkhonan/502#5]
@jkhonan I don't think I'm allowed to add people as you own the repo, can you add Qianying: here id is @heqianying, or maybe you already did.

**Comment by kaiiam** [comment]
Qianying is in we just need to add Jorge, once done we can close this.

**Comment by kaiiam** [comment]
@jkhonan can you also add Dr. Haiquan @haiquanua that way we can tag him in issues and ask for help using github I'm sure he'll be happy if we do that :).

**Comment by jkhonan** [comment]
@kaiiam I just resubmitted my request to have him join, and I sent Jorge his invite as well.

**Comment by kaiiam** [comment]
@jkhonan great!

**Comment by haiquanua** [comment]
Great work! @jkhonan @kaiiam. It is smart to use flagstaff data as the difference is expected.

**Comment by kaiiam** [comment]
Thank @haiquanua we'll let you know if we run into any major roadblocks!
