### ISSUE TITLE
Error Code in Pulling API Data

### ISSUE THREAD

**Issue by jkhonan** [jkhonan/502#7]
This is the error code that I get when I try to run the code to pull the data from rainlog.org/api.

"usage: pydevconsole.py [-h] [--out OUT] [--region REGION] start end
pydevconsole.py: error: the following arguments are required: start, end"

I think it's referring to lines 152-153, but I could be wrong. Any advice on what to change? @heqianying @kaiiam @jjramlu92

**Comment by kaiiam** [comment]
@jkhonan carefully read the error message, it's saying `the following arguments are required: start, end` This is a script that is meant to get data from somewhere, so therefore we need to pass it some inputs.

**Comment by kaiiam** [comment]
@jkhonan have a close look at line 98 the function `def get_readings_with_metadata(start, end, region):` which takes a start date end date and region, if we look at the top of the file there are even some regions pre-selected for us starting at line 20 even boxes for tucson and flagstaff with the 4 coors defined.

**Comment by jkhonan** [comment]
@kaiiam I've tried entering dates in start and end (both as just the number like 2015 and as '2015') and a region such as 'BOX_FLAGSTAFF' for lines 98 - 102, but I'm still getting the same error code. I also created the BOX_FLAGSTAFF coordinates based on google map data - do you think that's alright?

**Comment by kaiiam** [comment]
@jkhonan I went ahead and restarted from scratch from Dr. Li's version of the code. I've completed the first part and run the script to get the data. It's now ready for use in the https://github.com/jkhonan/502/tree/master/data folder with files for both Tucson and Flagstaff from jan 1 2015- jan 1 2020
